/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'female' : null } |
  { 'male' : null };
export interface HealthRecord {
  'age' : bigint,
  'bmi' : number,
  'isSmoker' : boolean,
  'bloodPressure' : bigint,
  'hemoglobin' : number,
  'glucose' : bigint,
  'gender' : Gender,
  'timestamp' : Time,
  'patientName' : string,
  'riskLevel' : RiskLevel,
  'riskScore' : number,
  'cholesterol' : bigint,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'moderate' : null };
export type Time = bigint;
export interface _SERVICE {
  'addRecord' : ActorMethod<
    [string, bigint, number, bigint, bigint, number, bigint, Gender, boolean],
    string
  >,
  'deleteRecord' : ActorMethod<[string], boolean>,
  'getAllRecords' : ActorMethod<[], Array<HealthRecord>>,
  'getRecordById' : ActorMethod<[string], HealthRecord>,
  'getRecordsByPatientName' : ActorMethod<[string], Array<HealthRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];