/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const Time = IDL.Int;
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'moderate' : IDL.Null,
});
export const HealthRecord = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'isSmoker' : IDL.Bool,
  'bloodPressure' : IDL.Nat,
  'hemoglobin' : IDL.Float64,
  'glucose' : IDL.Nat,
  'gender' : Gender,
  'timestamp' : Time,
  'patientName' : IDL.Text,
  'riskLevel' : RiskLevel,
  'riskScore' : IDL.Float64,
  'cholesterol' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        Gender,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
  'getRecordById' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
  'getRecordsByPatientName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HealthRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const Time = IDL.Int;
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const HealthRecord = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'isSmoker' : IDL.Bool,
    'bloodPressure' : IDL.Nat,
    'hemoglobin' : IDL.Float64,
    'glucose' : IDL.Nat,
    'gender' : Gender,
    'timestamp' : Time,
    'patientName' : IDL.Text,
    'riskLevel' : RiskLevel,
    'riskScore' : IDL.Float64,
    'cholesterol' : IDL.Nat,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          Gender,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
    'getRecordById' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
    'getRecordsByPatientName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HealthRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };