/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const Time = IDL.Int;
export const HealthRecord = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'isSmoker' : IDL.Bool,
  'bloodPressure' : IDL.Nat,
  'hemoglobin' : IDL.Float64,
  'glucose' : IDL.Nat,
  'gender' : Gender,
  'timestamp' : Time,
  'lastName' : IDL.Text,
  'riskScore' : IDL.Float64,
  'cholesterol' : IDL.Nat,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        Gender,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'getAllRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
  'getRecordById' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const Time = IDL.Int;
  const HealthRecord = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'isSmoker' : IDL.Bool,
    'bloodPressure' : IDL.Nat,
    'hemoglobin' : IDL.Float64,
    'glucose' : IDL.Nat,
    'gender' : Gender,
    'timestamp' : Time,
    'lastName' : IDL.Text,
    'riskScore' : IDL.Float64,
    'cholesterol' : IDL.Nat,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          Gender,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'getAllRecords' : IDL.Func([], [IDL.Vec(HealthRecord)], ['query']),
    'getRecordById' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };